### PR TITLE
return preprocessed dfs in-memory, saves time

### PR DESCRIPTION
**Pull request by nguyenhuyanhh**

### CODE REVIEW

**Review by tanvigupta97 — APPROVED** [review]
Good idea, fewer CSVs to deal with also

**Review by tanvigupta97 — COMMENTED** [review]
Wait, need to change other scripts also right

**Comment by nguyenhuyanhh** [comment]
you want to change train, test to use in-memory dfs also?

**Comment by tanvigupta97** [comment]
We can do that, but now that I think about it, I'm not sure of it is a good idea or not because of the memory usage. I think this is alright alr

**Comment by nguyenhuyanhh** [comment]
Don't think I would do it either. If it's alright just merge, I'm taking a 4-hr dinner break

**Pull request merged**
