### PR TITLE
Experimental encodings

### LINKED ISSUE #28: Experiment with other encodings
benchmark: 0.215246
the scores are based on doing one specific change at a time, compared to master benchmark
- [x] numerical encoding of suppliers based on frequency distribution: 0.218713
- [x] one-hot encoding of bill_of_materials' components based on component_type_id: 0.216899
- [x] one-hot encoding of material_id and others: 0.213848 (!!)
- [x] one-hot encoding of bill_of_materials' components based on component_type_id AND component_type: 0.215699
- [x] adding unique_feature and orientation: 0.213816 (!!)
- [x] tube_assembly_id after unique_feature and orientation: 0.210577 (!!!!)

### PR DESCRIPTION
**Pull request by nguyenhuyanhh**
Closes #28

### CODE REVIEW

**Comment by tanvigupta97** [comment]
Haha I'm not sure what this does rn

**Comment by nguyenhuyanhh** [comment]
don't merge yet haha, basically it adds material_id as a feature, beat rainy's benchmark

**Comment by nguyenhuyanhh** [comment]
trying other combos

**Comment by tanvigupta97** [comment]
Yup, I thought you might wanna modify more later, so I was unsure whether to merge now or not

**Comment by nguyenhuyanhh** [comment]
yeah, you could just refer to #28 for the checklist

all the best for quiz tmr!

**Comment by tanvigupta97** [comment]
Wow, manage to hit 0.2138! good job man
Thanks lol.

**Pull request closed without merging**
