### PR TITLE
Visualize supplier distribution

### PR DESCRIPTION
**Pull request by tanvigupta97**
Have a look, might wanna modify the threshold or something

### CODE REVIEW

**Review by nguyenhuyanhh — COMMENTED** [review]
I change a bit to speed-up the code, and sort the bars in reverse order

**Comment by nguyenhuyanhh** [comment]
Otherwise it looks good! regarding the cv, will look into it later after I'm done with my neural nets

**Comment by tanvigupta97** [comment]
Yup, I was trying to sort descending also, but my class ended lol

**Comment by tanvigupta97** [comment]
Wahhh I didn't know about this Counter thing

**Comment by nguyenhuyanhh** [comment]
LOL. anw thanks for the bring up
actually I was planning to use Counter for the suppliers function also, because Counter has a method most_common() which returns the top items, akin to what we coded

**Comment by nguyenhuyanhh** [comment]
Counter is OP

**Pull request merged**
