### PR TITLE
Initial refactoring -  split code into 4 files

### LINKED ISSUE #3: Split preprocessing, training and testing code

### PR DESCRIPTION
**Pull request by tanvigupta97**
Closes #3

### CODE REVIEW

**Comment by nguyenhuyanhh** [comment]
Could you add this line into .gitignore

```
.idea/
```
This would make sure all the files in .idea/ are not on github. They are specific to your setup =))

**Comment by nguyenhuyanhh** [comment]
Anw this is awesome 😁

**Review by nguyenhuyanhh — COMMENTED** [review]
Could you add this line into .gitignore
```
.idea/
```
This would make sure all the files in .idea/ are not on github. They are specific to your setup =))

**Comment by tanvigupta97** [comment]
Yup I realised that last night! Just forgot to do it

**Comment by nguyenhuyanhh** [comment]
Sure! Just do it and afterwards remove the whole folder from git :D

**Comment by tanvigupta97** [comment]
Yup done!

**Review by nguyenhuyanhh — COMMENTED** [review]
`git rm --cached .idea/`

**Pull request merged**
