### PR TITLE
update preprocess and wrapper

### LINKED ISSUE #9: Improve the training api further

### PR DESCRIPTION
**Pull request by nguyenhuyanhh**
Closes #9

### CODE REVIEW

**Comment by nguyenhuyanhh** [comment]
@tanvigupta97 don't merge first I need my supercomputer to verify results

**Comment by tanvigupta97** [comment]
Oh yeah I wanted to combine those 2 functions initially, they were too similar

**Comment by tanvigupta97** [comment]
Is it working properly now or need make any more changes?

**Comment by nguyenhuyanhh** [comment]
should be working properly now

**Review by tanvigupta97 — APPROVED** [review]

**Pull request merged**
