### PR TITLE
Random forest

### LINKED ISSUE #18: More models?

### PR DESCRIPTION
**Pull request by nguyenhuyanhh**
It's a quick one

Closes #18

### CODE REVIEW

**Comment by nguyenhuyanhh** [comment]
Very ugly code pls forgive

**Comment by tanvigupta97** [comment]
Should we change the function names for original train and predict to train_xg and predit_xg lol?

**Comment by nguyenhuyanhh** [comment]
good idea

**Comment by tanvigupta97** [comment]
How's the rf result btw?

**Comment by nguyenhuyanhh** [comment]
rf with 5000 trees = 0.260681, training time about 2x compared to xgboost on the same hardware

**Comment by nguyenhuyanhh** [comment]
no hyper-param tuning so I think it's understandably bad

**Comment by nguyenhuyanhh** [comment]
changed!

**Comment by tanvigupta97** [comment]
Oh alright. Also, I have an idea to change param to like args.model = 'rf' or 'xg'. From my understanding, the code right is like args.rf = True right?
I don't know, just an idea, because it can extended for more models that way I'm guessing

**Comment by nguyenhuyanhh** [comment]
Hmm technically can have a wrapper like train(train_set, model='') which either call train_xgb or train_rf. Return values could be complicated though, by default xgb saves a model file while rf does not

**Comment by tanvigupta97** [comment]
Ohh okay, nvm let's stick to this then

**Review by tanvigupta97 — APPROVED** [review]

**Comment by nguyenhuyanhh** [comment]
I'm reading into pickle, might be usable but anw

**Pull request merged**
